name: SimpleWarp
api-version: 1.16
authors:
  - Marylieh
  - SomeBottle
main: me.marylieh.simplewarp.SimpleWarp
version: 3.7

commands:
  setwarp:
  delwarp:
  warp:
  warps:
  simplewarp:
  position: