name: SimpleWarp
api-version: 1.19
authors:
  - Marylieh
  - SomeBottle
main: me.marylieh.simplewarp.SimpleWarp
version: 4.0

commands:
  setwarp:
  delwarp:
  warp:
  warps:
  simplewarp:
  position:
  sethome:
  delhome:
  home:
  homes:
